### ISSUE TITLE
Add file appender for log

### ISSUE THREAD

**Issue by CrissNamon** [CrissNamon/compaj#35]
CompaJ should write logs into file. It can be done by adding file appender for Log4J into `log4j.xml` in `resources`.
File should be located in `${user.dir}/CompaJ/logs`.

**Comment by CrissNamon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add file appender for log](https://trello.com/c/RgYAOfMt/29-add-file-appender-for-log)

**Comment by saurabhyadav1985** [comment]
I would like to contribute. Is this for CompaJ Lang module? https://github.com/CrissNamon/compaj/blob/main/lang/src/main/resources/log4j.properties
