### ISSUE TITLE
Fix tabs exception

### ISSUE THREAD

**Issue by CrissNamon** [CrissNamon/compaj#4]
Fix exception thrown after tab closing.
Steps to reproduce:
- open many different tabs (especially "Editor" tab)
- close tabs in random order
- try to open some tabs, exception could be thrown

**Comment by mohannaidu** [comment]
can you assign this to me? let me fix this

**Comment by mohannaidu** [comment]
Hi @CrissNamon .... this is a tough one. you basically can't add same node twice in the same parent problem. it is written as a rule here "_A node may occur at most once anywhere in the scene graph_" https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html

The advice given is to put the GUI into FXML and load into the scene. This allows for the reuse of tab. It gonna quite some effort to rewrite the GUI code into FXML file and inject values and load them up. I don't think I have the time. But I think you get the gist on how to proceed forward.

**Comment by CrissNamon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tabs exception](https://trello.com/c/TUYmx0GX/11-tabs-exception)
